### PR TITLE
Rectangle abstracted as an interface

### PR DESCRIPTION
**Pull request by eadwright**
Proposed implementation for issue https://github.com/davidmoten/rtree/issues/55 .

### CODE REVIEW

**Comment by davidmoten** [comment]
Thanks for the PR @eadwright! You're right it needs some attention. I think we can enhance this a bit. If we make Rectangle an interface then to save allocating an mbr Rectangle as a field in each Point we would also make Point implement Rectangle so that the `Point.mbr()` call would just return `this`. That way we also don't need the little dance in `Util.mbr` that is in the PR.

**Comment by eadwright** [comment]
I think I probably rushed my proposed solution a bit. I like what you're saying, my use cases stores points so being able to store points which can walk and talk like rectangles but only have the cost of a point associated with them would be a bonus.

**Comment by davidmoten** [comment]
Yep.  Do you want to amend this PR or get me to do it?

**Comment by davidmoten** [comment]
Hi @eadwright, as I haven't heard from you I might skip this PR because it has some changes  I don't want (Util.mbr() for instance) and implement myself as per our discussion.

**Comment by davidmoten** [comment]
released rtree 0.8-RC9 to maven central with discussed mods. Please try it out.

**Comment by eadwright** [comment]
Hi, sorry I think our time-difference was working against us :) Just looked at the RC9 source, I like what you've done! Will test it shortly. Should make quite a difference, speed & memory footprint. Nice bang for the buck.

**Comment by eadwright** [comment]
Further testing, just created in my codebase a unit test for the serialization, I wanted to debug and see what the data structure looks like. Looks perfect, my points are Point instances with two floats, couldn't be "cheaper". Well done. Closing.

**Comment by davidmoten** [comment]
Thanks for testing it out and for the idea, glad it works.

**Pull request closed without merging**
